name: Deploy to cPanel via SCP

on:
  push:
    branches:
      - uat  # Trigger the workflow only on the uat branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Upload files via SCP
      run: |
        tar -czvf project.tar.gz ./*
        scp -o StrictHostKeyChecking=no project.tar.gz git@drapefittest.com:/home/drapefittest/public_html/

 
