name: Deploy to cPanel

on:
  push:
    branches:
      - uat  # Trigger the workflow only on the uat branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        ftp-port: ${{ secrets.FTP_PORT }}
        local-dir: ./  # Path to your local directory in the repo
        server-dir: /public_html/  # Path on your FTP server
